app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

Route::get('/', function() {
    return Redirect::route('home');
});

Route::get('/home',array('as'=>'home','uses'=>'PagesCommonController@home'));
Route::get('/contact-us',array('as'=>'contact_us','uses'=>'PagesCommonController@contact_us'));
Route::get('/about-us',array('as'=>'about-us','uses'=>'PagesCommonController@about_us'));
Route::get('/terms',array('as'=>'terms','uses'=>'PagesCommonController@terms'));
Route::get('/privacy-policy',array('as'=>'privacy_policy','uses'=>'PagesCommonController@privacy_policy'));
Route::get('/faq',array('as'=>'faq','uses'=>'PagesCommonController@faq'));
Route::get('/why-choose-us',array('as'=>'why_choose_us','uses'=>'PagesCommonController@why_choose_us'));
Route::get('/customize-tour',array('as'=>'customize_tour','uses'=>'PagesCustomizeTourController@customize_tour'));

//Customize
Route::get('customize-tour/product/{destination_id}',array('as'=>'customize_tour.show.product','uses'=>'PagesCustomizeTourController@show_product'));
//Travellers
Route::resource('travellers', 'TravellersController');
Route::get('travellers/delete/{id}',array('as'=>'travellers.delete','uses'=>'TravellersController@delete'));
//NewsletterRegistration
Route::resource('newsletter_registrations', 'NewsletterRegistrationsController');
Route::get('newsletter-registrations/thank-you', array('as'=>'newsletter_registrations.thank_you','uses'=>'PagesCommonController@newsletterRegistrationThankYou'));
Route::get('newsletter/cancel-complete', array('as'=>'newsletters.cancel.complete','uses'=>'PagesCommonController@newsletterCancelComplete'));
Route::get('newsletters/cancel/{email}',array('as'=>'newsletters.cancel','uses'=>'NewslettersController@cancel'));
//Reviews
Route::resource('reviews', 'ReviewsController');
Route::get('reviews/{id}/delete',array('as'=>'reviews.delete','uses'=>'ReviewsController@delete'));
Route::get('reviews/setStatus/{id}/{status}',array('as'=>'reviews.setStatus','uses'=>'reviewsController@setStatus'));
//Contact
Route::post('/contact-us',array('as'=>'contact_us.submitContact','uses'=>'PagesCommonController@submitContact'));
//Payment
Route::resource('payments', 'PaymentsController');
Route::post('/payments/qaptcha',array('uses'=>'PaymentsController@qaptcha'));

Route::get('/login', function() {
    if(!Auth::check()){
        return View::make('login.login');
    }else{
        return Redirect::to('contents');
    }
});
Route::get('/logout', function() {
    Auth::logout();
    return Redirect::to('/home');
});

Route::post('/login', function() {
    $user=['email'=>Input::get('email'),'password'=>Input::get('password')];
    $validator = Validator::make($data = $user, User::$rules);
    if ($validator->passes()) {
        // Try to log the user in.
        if (Auth::attempt($user)) {
            return Redirect::intended('contents')->with('message', 'You have logged in successfully');
        }
        $errors =  new Illuminate\Support\MessageBag;
        $errors->add('password','Email and/or password invalid.');
        return Redirect::to('login')->withErrors($errors)->withInput(Input::except('password'));
    } else {
        // Something went wrong.
        return Redirect::back()->withErrors($validator)->withInput(Input::except('password'));
    }
});
Route::group(array('before' => 'auth'), function() {
    Route::resource('contents', 'ContentsController');
    Route::resource('destinations', 'DestinationsController');
    
    Route::get('newsletters/send/{id}', array('as' => 'newsletters.send', 'uses' => 'NewslettersController@send'));
    Route::resource('newsletters', 'NewslettersController');
    
    Route::resource('images', 'ImagesController');
    Route::get('/destinations/{destinations_id}/images',array('as'=>'images.relations','uses' => 'ImagesController@relations'));
    
    Route::resource('promotions', 'PromotionsController');
    Route::get('/destinations/{destinations_id}/promotions',array('as'=>'promotions.relations','uses' => 'PromotionsController@relations'));
});

app/models/Image.php
<?php

class Image extends \Eloquent {

    // Add your validation rules here
    public static $rules = [
        'destinations_id'=>'required|min:1|numeric',
        'file' => 'required|mimes:jpeg,bmp,png'
    ];
    // Don't forget to fill this array
    protected $fillable = ['destinations_id', 'file'];

}

app/controllers/ImagesController.php
<?php

class ImagesController extends \BaseController {

    /**
     * Display a listing of images
     *
     * @return Response
     */
    public function index() {
        $images = Image::all();

        return View::make('images.index', compact('images'));
    }

    /**
     * Show the form for creating a new image
     *
     * @return Response
     */
    public function create() {
        return View::make('images.create')->with('destinations_id', Input::get('destinations_id'));
    }

    /**
     * Store a newly created image in storage.
     *
     * @return Response
     */
    public function store() {
        $validator = Validator::make($data = Input::all(), Image::$rules);

        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator)->withInput();
        }

        $filename = "destination_" . $data['destinations_id'] . "_" . time() . "." . $data['file']->getClientOriginalExtension();
        ;

        $img = ImageManipulation::make($file = Input::file('file'))->save('uploads/images/original/' . $filename);
        $img->backup();

        $img->fit(770, 500)->save('uploads/images/fullsize/' . $filename);

        $img->reset();
        $img->fit(440, 295)->save('uploads/images/bigsize/' . $filename);
        
        $img->reset();
        $img->fit(360, 240)->save('uploads/images/mediumsize/' . $filename);

        $img->reset();
        $img->fit(150)->save('uploads/images/thumbnails/' . $filename);

        $data = ['destinations_id' => $data['destinations_id'], 'file' => $filename];

        Image::create($data);

        Session::flash('success_message', 'A new Image has been stored.');

        return Redirect::route('images.relations', [$data['destinations_id']]);
    }

    /**
     * Display the specified image.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id) {
        $image = Image::findOrFail($id);

        return View::make('images.show', compact('image'));
    }

    /**
     * Show the form for editing the specified image.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id) {
        $image = Image::find($id);

        return View::make('images.edit', compact('image'));
    }

    /**
     * Update the specified image in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id) {
        $image = Image::findOrFail($id);

        $validator = Validator::make($data = Input::all(), Image::$rules);

        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator)->withInput();
        }

        $image->update($data);

        return Redirect::route('images.index');
    }

    /**
     * Remove the specified image from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id) {
        $image = Image::find($id);

        $files = array(
            "uploads/images/original/" . $image->file,
            "uploads/images/fullsize/" . $image->file,
            "uploads/images/mediumsize/" . $image->file,
            "uploads/images/thumbnails/" . $image->file
        );
        File::delete($files);

        Image::destroy($id);

        Session::flash('success_message', 'The specified image has been removed.');

        return Redirect::route('images.relations', array($image->destinations_id));
    }

    public function relations($id) {
        $destination = Destination::findOrFail($id);

        $images = Image::where('destinations_id', $id)->get();

        return View::make('images.index', compact('images'))->with('destination', $destination);
    }

}

app/views/images/create.blade.php
@extends('layouts.master')
@section('h1')
Create image
@stop

@section('content')
{{link_to_route('images.relations', "Back", $parameters = array($destinations_id), $attributes = array('class'=>'btn btn-default'))}}
<hr>

{{Form::open(array('route' => 'images.store','method'=>'post','role'=>'form','files'=>true)) }}
<div class="form-group">
    {{Form::label('file', 'Photo')}}
    @include('includes.error_notification', array('field'=>'file'))
    {{Form::file('file',array('class'=>'form-control'))}}
    {{Form::hidden('destinations_id',$destinations_id);}}
</div>
{{Form::submit('Upload',array('class'=>'btn btn-primary'))}}
{{ Form::close() }}
@stop

app/views/images/edit.blade.php
@extends('layouts.master')
@section('h1')
Edit image
@stop

@section('content')
{{link_to_route('destinations.show', "Back", $parameters = array($destination_id), $attributes = array('class'=>'btn btn-default'))}}
<hr>

{{Form::open(array('route' => 'images.store','method'=>'post','role'=>'form','files'=>true))}}
<div class="form-group">
    {{Form::label('file', 'Photo')}}
    @include('includes.error_notification', array('field'=>'file'))
    {{Form::file('file',array('class'=>'form-control'))}}
    {{Form::hidden('destination_id',$destination_id);}}
</div>
{{Form::submit('Upload',array('class'=>'btn btn-primary'))}}
{{ Form::close() }}
@stop

app/views/images/index.blade.php
@extends('layouts.master')
@section('h1')
Images for {{$destination->name}} ({{$destination->code}})
@stop
@section('content')
{{link_to_route('destinations.index', "Back", $parameters = array(), $attributes = array('class'=>'btn btn-default'))}}
<hr>
@include('includes.success_notification')
<div class="row">
    <div class="col-lg-12">
        {{link_to_route('images.create', "Add a photo", $parameters = array('destinations_id'=>$destination->id), $attributes = array('class'=>'btn btn-success'))}}
    </div>
</div>
<hr>
<div class="row">
    <div class="col-lg-12">
        <p><strong>Images:</strong></p>
@if(sizeof($images)==0)
    <p>You haven't add any images to this destination.</p>
@else
    @foreach($images as $image)
    <a href='{{ route('images.show', $parameters = array($image->id))}}'><img class='thumbnail' src="{{asset("uploads/images/thumbnails/".$image->file)}}" /></a>
    @endforeach
@endif
    </div>
</div>

@stop

app/views/images/show.blade.php
@extends('layouts.master')
@section('h1')
Image
@stop
@section('content')
{{link_to_route('images.relations', "Back", $parameters = array($image->destinations_id), $attributes = array('class'=>'btn btn-default'))}}
<hr>
{{Form::open(array('route' => array('images.destroy', $image->id),'method'=>'delete'))}}
{{Form::submit('Delete',array('class'=>'btn btn-danger','onClick'=>'return (confirm("Are you sure?"))'))}}
{{Form::close()}}
<hr>
 <p><strong>Thumbnail:</strong></p>
<img class='thumbnail' src='{{asset('uploads/images/thumbnails/'.$image->file)}}' />
<br><br>
<p><strong>Medium size:</strong></p>
<img class='thumbnail' src='{{asset('uploads/images/mediumsize/'.$image->file)}}' />
<br><br>
<p><strong>Full size:</strong></p>
<img class='thumbnail' src='{{asset('uploads/images/fullsize/'.$image->file)}}' />
<br><br>
<p><strong>Original:</strong></p>
<img class='thumbnail' src='{{asset('uploads/images/original/'.$image->file)}}' />
@stop